
package com.fym.gui;
import java.util.HashSet;
import java.util.HashMap;
import java.util.UUID;
import com.fym.model.*;
import java.time.ZoneId;




/**
 *
 * @author v
 */
public class addTransaction extends javax.swing.JFrame {
    private BudgetManager budgetManager;

    /**
     * Creates new form addTransaction
     */
    public addTransaction(BudgetManager budgetManager) {
        this.budgetManager = budgetManager;
        initComponents();
        showComboCategory();
        showComboAccount();
        addTab();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tab = new javax.swing.JTabbedPane();
        addTransaction = new javax.swing.JPanel();
        typeText = new javax.swing.JLabel();
        accountText = new javax.swing.JLabel();
        amountText = new javax.swing.JLabel();
        categoryText = new javax.swing.JLabel();
        dateTimeText = new javax.swing.JLabel();
        noteText = new javax.swing.JLabel();
        type = new javax.swing.JComboBox<>();
        account = new javax.swing.JComboBox<>();
        amount = new javax.swing.JTextField();
        category = new javax.swing.JComboBox<>();
        dateTime = new com.toedter.calendar.JDateChooser();
        note = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabMouseClicked(evt);
            }
        });

        typeText.setText("Type     :");

        accountText.setText("Account:");

        amountText.setText("Amount:");

        categoryText.setText("Category:");

        dateTimeText.setText("Date Time:");

        noteText.setText("Note:");

        type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Income", "Expense" }));

        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addTransactionLayout = new javax.swing.GroupLayout(addTransaction);
        addTransaction.setLayout(addTransactionLayout);
        addTransactionLayout.setHorizontalGroup(
            addTransactionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addTransactionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addTransactionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(typeText)
                    .addComponent(accountText)
                    .addComponent(amountText)
                    .addComponent(categoryText)
                    .addComponent(dateTimeText)
                    .addComponent(noteText))
                .addGap(30, 30, 30)
                .addGroup(addTransactionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(addTransactionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(account, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(type, javax.swing.GroupLayout.Alignment.LEADING, 0, 112, Short.MAX_VALUE)
                        .addComponent(amount, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(category, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(note))
                .addGap(271, 271, 271))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addTransactionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addButton)
                .addGap(27, 27, 27)
                .addComponent(cancelButton)
                .addGap(14, 14, 14))
        );
        addTransactionLayout.setVerticalGroup(
            addTransactionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addTransactionLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(addTransactionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(typeText)
                    .addComponent(type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(addTransactionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(accountText)
                    .addComponent(account, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(addTransactionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(amountText)
                    .addComponent(amount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(addTransactionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(categoryText)
                    .addComponent(category, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(addTransactionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateTimeText)
                    .addComponent(dateTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(addTransactionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(noteText)
                    .addComponent(note, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(addTransactionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButton)
                    .addComponent(cancelButton))
                .addGap(25, 25, 25))
        );

        tab.addTab("Transaction", addTransaction);

        exitButton.setText("X");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tab, javax.swing.GroupLayout.DEFAULT_SIZE, 641, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(exitButton)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tab, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        budgetManager.addTransaction((String)type.getSelectedItem(),budgetManager.getAccounts().get(UUID.fromString((String)account.getSelectedItem())), (String)category.getSelectedItem(), Float.parseFloat(amount.getText()), note.getText(), true, dateTime.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate());
        clearText();
    }//GEN-LAST:event_addButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        clearText();

    }//GEN-LAST:event_cancelButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_exitButtonActionPerformed

    private void tabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tabMouseClicked

    /**
     * @param args the command line arguments
     */

    private void showComboCategory(){
        HashSet<String> data = budgetManager.getCategories();
        for(String c: data){
            category.addItem(c);
        }
        
    }
    private void showComboAccount(){
        HashMap<UUID,Account> data = budgetManager.getAccounts();
        for(Account c: data.values()){
            account.addItem(c.getID().toString());
        }
        
    }
    private void addTab(){
        addTranfer addTranfer = new addTranfer(budgetManager);
        tab.addTab("Tranfer",addTranfer);
    }
    private void clearText(){
        amount.setText(null);
        dateTime.setDate(null);
        note.setText(null);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> account;
    private javax.swing.JLabel accountText;
    private javax.swing.JButton addButton;
    private javax.swing.JPanel addTransaction;
    private javax.swing.JTextField amount;
    private javax.swing.JLabel amountText;
    private javax.swing.JButton cancelButton;
    private javax.swing.JComboBox<String> category;
    private javax.swing.JLabel categoryText;
    private com.toedter.calendar.JDateChooser dateTime;
    private javax.swing.JLabel dateTimeText;
    private javax.swing.JButton exitButton;
    private javax.swing.JTextField note;
    private javax.swing.JLabel noteText;
    private javax.swing.JTabbedPane tab;
    private javax.swing.JComboBox<String> type;
    private javax.swing.JLabel typeText;
    // End of variables declaration//GEN-END:variables
}
